/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductRegistrationIndexImport } from './routes/product-registration/index'
import { Route as EventAnalyzerIndexImport } from './routes/event-analyzer/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductRegistrationIndexRoute = ProductRegistrationIndexImport.update({
  id: '/product-registration/',
  path: '/product-registration/',
  getParentRoute: () => rootRoute,
} as any)

const EventAnalyzerIndexRoute = EventAnalyzerIndexImport.update({
  id: '/event-analyzer/',
  path: '/event-analyzer/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/event-analyzer/': {
      id: '/event-analyzer/'
      path: '/event-analyzer'
      fullPath: '/event-analyzer'
      preLoaderRoute: typeof EventAnalyzerIndexImport
      parentRoute: typeof rootRoute
    }
    '/product-registration/': {
      id: '/product-registration/'
      path: '/product-registration'
      fullPath: '/product-registration'
      preLoaderRoute: typeof ProductRegistrationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/event-analyzer': typeof EventAnalyzerIndexRoute
  '/product-registration': typeof ProductRegistrationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/event-analyzer': typeof EventAnalyzerIndexRoute
  '/product-registration': typeof ProductRegistrationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/event-analyzer/': typeof EventAnalyzerIndexRoute
  '/product-registration/': typeof ProductRegistrationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/event-analyzer' | '/product-registration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/event-analyzer' | '/product-registration'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/event-analyzer/'
    | '/product-registration/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventAnalyzerIndexRoute: typeof EventAnalyzerIndexRoute
  ProductRegistrationIndexRoute: typeof ProductRegistrationIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventAnalyzerIndexRoute: EventAnalyzerIndexRoute,
  ProductRegistrationIndexRoute: ProductRegistrationIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/event-analyzer/",
        "/product-registration/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/event-analyzer/": {
      "filePath": "event-analyzer/index.tsx"
    },
    "/product-registration/": {
      "filePath": "product-registration/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
